logging:
    level:
        sql: debug
        web: debug
server:
    port: 8092
spring:
    application:
        name: login-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/cloud2024?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
    mvc:
        servlet:
            multipart:
                max-file-size: '10MB '
                max-request-size: 100MB

mybatis-plus:
    type-aliases-package: com.login.demologin.entity
    mapper-locations: mappers/*.xml
    global-config:
        db-config:
            id-type: auto
jwt:
    config:
        secret: token!Q@W#E$R

